spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb
    username: root
    password: 123456
  data:
    solr:
      host: http://127.0.0.1:8080/solr

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.pinyougou.solrutil.entity
  mapper-locations: classpath:/com/pinyougou/solrutil/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增" , 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true

server:
  port: 8888