demo:
  service:
    version: 1.0.0
dubbo:
  application:
    id: pinyougou-shop-web
    name: pinyougou-shop-web
    qos-port: 20102
  protocol:
    id: dubbo
    name: dubbo
  registry:
    address: 192.168.200.102:2181
    id: my-consumer2
    protocol: zookeeper
    timeout: 30000
server:
  port: 9102
spring:
  application:
    name: pinyougou-shop-web
  server:
    MaxFileSize: 300MB
    MaxRequestSize: 500MB
    acceptorThreadCount: 4
    compression: 'on'
    connectionTimeout: 10000
    maxConnections: 10000
    maxSpareThreads: 50
    maxThreads: 1000
    minSpareThreads: 50
    port: 9102
    protocol: org.apache.coyote.http11.Http11Nio2Protocol
    redirectPort: 443
