demo:
  service:
    version: 1.0.0
dubbo:
  application:
    id: pinyougou-shop-web
    name: pinyougou-shop-web
  protocol:
    id: dubbo
    name: dubbo
    port: 20081
  registry:
    address: 192.168.200.102:2181
    id: my-consumer2
    protocol: zookeeper
    timeout: 30000
server:
  port: 9102
spring:
  application:
    name: pinyougou-shop-web
