demo:
  service:
    version: 1.0.0
dubbo:
  application:
    id: pinyougou-manager-web
    name: pinyougou-manager-web
    qos-port: 22223
  protocol:
    id: dubbo
    name: dubbo
  registry:
    address: 192.168.200.102:2181
    id: my-consumer1
    protocol: zookeeper
    timeout: 30000
  scan:
    base-packages: com.pinyougou.manager.controller
  consumer:
    check: false
server:
  port: 9101
spring:
  application:
    name: pinyougou-manager-web
